### PR TITLE
complete culture properties

### PR DESCRIPTION
**Pull request by pricelessbrewing**
Resolving issue #139

### CODE REVIEW

**Comment by pricelessbrewing** [comment]
Hey @krutilin What's the situation with the travis CI tests? I've noticed they don't seem to be working automatically anymore?

**Comment by krutilin** [comment]
https://travis-ci.community/t/known-issue-travis-ci-reports-expected-waiting-for-status-to-be-reported-on-the-github-status-api-but-the-status-never-arrives/1154

trying to fix

**Comment by krutilin** [comment]
fixed

**Comment by pricelessbrewing** [comment]
Can you merge this?

**Pull request merged**
