### PR TITLE
Suggestion to rename attenuation to the attenuation_range in the CultureInformation

### PR DESCRIPTION
**Pull request by krutilin**
to remove duplication of the attenuation field.

### CODE REVIEW

**Comment by pricelessbrewing** [comment]
What other attenuation field? 

Agreed, culture should be attenuation range. But we should also have apparent attenuation as a property of recipe.json, or fermentation.

**Comment by krutilin** [comment]
For the recipe calculation, we can use attenuation from the CultureAdditionType. And for the information about culture in store\inventory, we use attenuation_range, because it can be different depends from several reasons.

**Comment by pricelessbrewing** [comment]
Sorry to clutter the PR, but I think best practice would be to use attenuation_range for both the cultureAddition, and the ingredient/inventory etc. 

The only instance of a non range property would be for the recipe, but that should be calculated from the OG and FG, and should be a property of the recipe as it's a function of the mash parameters, grain bill, and what culture is used as well as fermentation characteristics.

**Comment by pricelessbrewing** [comment]
Going to go ahead and approve this, and issue a new issue to add apparent_attenuation to recipe.json near the other recipe properties like og/fg/srm/pH etc.

**Pull request merged**
