### PR TITLE
Replacing ambiguous references ('supplier'|'laboratory') by 'producer'

### PR DESCRIPTION
**Pull request by PierreSmits**
Per discussion on https://gitter.im/beerjson/beerjson

### CODE REVIEW

**Comment by PierreSmits** [comment]
related ticket  #136

**Comment by pricelessbrewing** [comment]
Let's add producer to the misc ingredients as well so they all match.

**Comment by PierreSmits** [comment]
Is there something else that needs to be done, before this can be committed?

**Comment by krutilin** [comment]
@PierreSmits please generate and commit updated docs:
`npm run gen-docs`

**Comment by PierreSmits** [comment]
I ran the 'npm run gen-docs' command.

But got an error:
`0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/usr/local/Cellar/node/12.8.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'gen-docs'
1 verbose cli ]
2 info using npm@6.10.3
3 info using node@v12.8.0
4 verbose run-script [ 'pregen-docs', 'gen-docs', 'postgen-docs' ]
5 info lifecycle beerjson@1.0.0~pregen-docs: beerjson@1.0.0
6 info lifecycle beerjson@1.0.0~gen-docs: beerjson@1.0.0
7 verbose lifecycle beerjson@1.0.0~gen-docs: unsafe-perm in lifecycle true
8 verbose lifecycle beerjson@1.0.0~gen-docs: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/nl04748/dev/beerjson/node_modules/.bin:/usr/local/bin:/usr/bin:/bin$
9 verbose lifecycle beerjson@1.0.0~gen-docs: CWD: /Users/nl04748/dev/beerjson
10 silly lifecycle beerjson@1.0.0~gen-docs: Args: [
10 silly lifecycle   '-c',
10 silly lifecycle   'node js/gen-docs.js ; prettier --write ./types/ts/beerjson.d.ts ; prettier --write ./types/flow-typed/beerjson.js'
10 silly lifecycle ]
11 info lifecycle beerjson@1.0.0~gen-docs: Failed to exec gen-docs script
12 verbose stack Error: beerjson@1.0.0 gen-docs: `node js/gen-docs.js ; prettier --write ./types/ts/beerjson.d.ts ; prettier --write ./types/flow-typed/beerjson.js`
12 verbose stack spawn ENOENT
12 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:48:18)
12 verbose stack     at ChildProcess.emit (events.js:203:13)
12 verbose stack     at maybeClose (internal/child_process.js:1021:16)
12 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
13 verbose pkgid beerjson@1.0.0
14 verbose cwd /Users/nl04748/dev/beerjson
15 verbose Darwin 17.7.0
16 verbose argv "/usr/local/Cellar/node/12.8.0/bin/node" "/usr/local/bin/npm" "run" "gen-docs"
17 verbose node v12.8.0
18 verbose npm  v6.10.3
19 error code ELIFECYCLE
20 error syscall spawn
21 error file sh
22 error errno ENOENT
23 error beerjson@1.0.0 gen-docs: `node js/gen-docs.js ; prettier --write ./types/ts/beerjson.d.ts ; prettier --write ./types/flow-typed/beerjson.js`
23 error spawn ENOENT
24 error Failed at the beerjson@1.0.0 gen-docs script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 1, true ]

`

**Comment by krutilin** [comment]
Sorry, can't reproduce the error, but docs look updated. Also, I fixed tests and now pr LGTM.

**Comment by PierreSmits** [comment]
Thanks.

**Comment by PierreSmits** [comment]
Should this lead to a new release?

**Pull request merged**
