### PR TITLE
Adding equipment.json

### PR DESCRIPTION
**Pull request by pricelessbrewing**
Addresses #19 Please review @krutilin @superroma. 

Questions: Should additional properties be allowed to maximize compatibility between software, or disallowed to force the schema layout? Honestly I can't think of much else that would be _necessary_ to include in the equipment profile, although there's some stuff I would like to add like heat loss per hour.

### CODE REVIEW

**Comment by krutilin** [comment]
I think that additional props should not be allowed, anyway, beerjson is open source format. And if someone's software takes in to account very specific params it is possible to add these params via issue or pull request.

As about this pull, please 
1) add tests for the equipment entity (tests/generic at least)  
2) fix whitespace formatting to 2 spaces.

**Comment by superroma** [comment]
> I think that additional props should not be allowed, anyway, beerjson is open source format. And if someone's software takes in to account very specific params it is possible to add these params via issue or pull request.

I don't think it is reasonable to add any app-specific info to the format. And if we restrict schema, then any app-specific info would have to be placed somewhere else, meaning BeerJSON would not be a primary storage format, but just data interchange format. Which is not good either.

I think we should allow "additionalData" entry with free-form content in relevant places, so this data is available to those who can handle it.

**Comment by krutilin** [comment]
Sounds reasonable. This will not break validation for existing fields but will do beerjson more open.

**Comment by pricelessbrewing** [comment]
Please review generic test. Not sure how to go about the real test, or add it to the test.js file. A bit above me atm.

**Comment by krutilin** [comment]
Reviewed. Please check your fork with test and instructions.

**Pull request merged**
