### PR TITLE
Add prettier formatting rules

### PR DESCRIPTION
**Pull request by krutilin**
And reformat all json stuff. 
Now it is possible to run prettier on precommit using `npm run precommit`.
Or it will run automatically after `npm i` with husky and git hooks after each commit.

### CODE REVIEW

**Comment by pricelessbrewing** [comment]
Looks good to me, but not going to review. Just so I'm clear, it should be 

npm run gen-docts, run precommit, test -- -u?

**Comment by krutilin** [comment]
Prettier should work out of the box each time you push commit button. The general algorithm is the following:
1) npm i
2) some changes in code or JSON schemas
3) run tests
4) update docs
5) stage files
6) npm run precommit to fix formatting, but this step is not necessary. Because it will be automatically executed after you push commit button.
7) commit

**Comment by pricelessbrewing** [comment]
error code below attempting to run precommit. 

beerjson>npm run precommit
npm ERR! missing script: precommit

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Mark\AppData\Roaming\npm-cache\_logs\2018-09-05T17_56_08_933Z-debug.log


error log below

> 0 info it worked if it ends with ok
> 1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
> 1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
> 1 verbose cli   'run',
> 1 verbose cli   'precommit' ]
> 2 info using npm@5.6.0
> 3 info using node@v8.11.2
> 4 verbose stack Error: missing script: precommit
> 4 verbose stack     at run (C:\Program Files\nodejs\node_modules\npm\lib\run-script.js:151:19)
> 4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\run-script.js:61:5
> 4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:115:5
> 4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:402:5
> 4 verbose stack     at checkBinReferences_ (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:357:45)
> 4 verbose stack     at final (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:400:3)
> 4 verbose stack     at then (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:160:5)
> 4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:348:12
> 4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:78:16
> 4 verbose stack     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)
> 5 verbose cwd D:\Software\Github\PricelessbrewingBeerjson\beerjson
> 6 verbose Windows_NT 10.0.17134
> 7 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "precommit"
> 8 verbose node v8.11.2
> 9 verbose npm  v5.6.0
> 10 error missing script: precommit
> 11 verbose exit [ 1, true ]
> 

```

**Comment by krutilin** [comment]
Did you `npm i` before?

**Comment by krutilin** [comment]
Let me check it on the Win machine because it works on mac and ubuntu.

Meanwhile, please check that your package.json is updated to the latest from the master branch and include following
`  "scripts": {
    "test": "jest",
    "gen-docs": "node js/gen-docs.js",
    "precommit": "lint-staged"
  }`

**Comment by krutilin** [comment]
@pricelessbrewing I checked on Win machine, it works:

```
C:\Projects\Beerjson>yarn precommit
yarn run v1.9.4
$ lint-staged
 ↓ Running tasks for *.{js,json,css,md} [skipped]
   → No staged files match *.{js,json,css,md}
Done in 0.65s.
```

**Comment by pricelessbrewing** [comment]
Still no such luck. Any ideas?


D:\Software\Github\PricelessbrewingBeerjson\beerjson>npm i
> 
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules\fsevents):
> npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
> 
> up to date in 3.282s

 D:\Software\Github\PricelessbrewingBeerjson\beerjson>npm run precommit
> 
> > beerjson@1.0.0 precommit D:\Software\Github\PricelessbrewingBeerjson\beerjson
> > lint-staged
> 
> events.js:183
>       throw er; // Unhandled 'error' event
>       ^
> 
> Error: spawn git ENOENT
>     at _errnoException (util.js:992:11)
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
>     at onErrorNT (internal/child_process.js:372:16)
>     at _combinedTickCallback (internal/process/next_tick.js:138:11)
>     at process._tickCallback (internal/process/next_tick.js:180:9)
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! beerjson@1.0.0 precommit: `lint-staged`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the beerjson@1.0.0 precommit script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\Users\Mark\AppData\Roaming\npm-cache\_logs\2018-09-09T22_28_52_971Z-debug.log

**Comment by superroma** [comment]
I cannot reproduce on several machines around.
It seems like you have problems with git. Can you reinstall it or update to the new version.

**Comment by pricelessbrewing** [comment]
Yup that worked, weird. Thanks

**Pull request merged**
