### PR TITLE
ISSUE-118 Adding GraphicType to allow for labels 

### PR DESCRIPTION
**Pull request by ellisgl**
ISSUE-118 Adding GraphicType to allow for labels and other graphics to be applied to vessels.

### CODE REVIEW

**Comment by krutilin** [comment]
Add ajv.addSchema(require('../json/packaging_graphic')) to the js/validation.js. Schema validator can't find new packaging_graphic type and fail on this step. It is not obvious, I also spend several hours figuring out why tests failed.

**Comment by ellisgl** [comment]
@krutilin Thank you!

**Review by krutilin — COMMENTED** [review]
I like the idea to save photos of the beer's package. But maybe we should add some optional URL field for saving images to some CDN or cloud, because saving as raw base64_data looks like overkill nowadays.

**Comment by ellisgl** [comment]
@krutilin should we do like 4 URLs, to help prevent link rot?

**Comment by krutilin** [comment]
May it be better to use an array of URLS? Because url1, url2, url3... will work too, but it looks a bit strange.
```
    "URLS": {
      "type": "array",
      "items": {
        "type": "string"
      }
```

**Review by krutilin — APPROVED** [review]
lgtm

**Pull request merged**
